import random

print("welcome to the character generater!")
print("Let's name the brave adventurers: ")
name1=input("character1: ")
name2=input("character2: ")
name3=input("character3: ")
name4=input("character4: ")
name5=input("character5: ")
name1_num= random.randint(1,3)
name2_num= random.randint(1,3)
name3_num= random.randint(1,3)
name4_num= random.randint(1,3)
name5_num= random.randint(1,3)
print("***YOUR CHARACTERS ARE COMPLETED!!!***")
print()
print()

if (name1_num == 1):
        print(name1,"is a Wizard!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=3*random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name1_num == 2):
        print(name2,"is a Warrior!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=3*random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name1_num == 3):
        print(name3,"is a Potato!")
        health=random.randint(5,10)
        print("Health: " ,3*health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic)  
        print('---------------') 

if (name2_num == 1):
        print(name1,"is a Wizard!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=3*random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name2_num == 2):
        print(name2,"is a Warrior!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=3*random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name2_num == 3):
        print(name3,"is a Potato!")
        health=random.randint(5,10)
        print("Health: " ,3*health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic) 
        print('---------------') 

if (name3_num == 1):
        print(name1,"is a Wizard!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=3*random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name3_num == 2):
        print(name2,"is a Warrior!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=3*random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name3_num == 3):
        print(name3,"is a Potato!")
        health=random.randint(5,10)
        print("Health: " ,3*health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic) 
        print('---------------') 

if (name4_num == 1):
        print(name1,"is a Wizard!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=3*random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name4_num == 2):
        print(name2,"is a Warrior!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=3*random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name4_num == 3):
        print(name3,"is a Potato!")
        health=random.randint(5,10)
        print("Health: " ,3*health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic) 
        print('---------------')   

if (name5_num == 1):
        print(name1,"is a Wizard!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=3*random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name5_num == 2):
        print(name2,"is a Warrior!")
        health=random.randint(5,10)
        print("Health: " ,health)
        strength=3*random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic)
        print('---------------')
elif (name5_num == 3):
        print(name3,"is a Potato!")
        health=random.randint(5,10)
        print("Health: " ,3*health)
        strength=random.randint(5,10)
        print("Strength: ",strength)
        magic=random.randint(5,10)
        print("Magic :" ,magic) 
        print('---------------')               

 